# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "microservicio-autenticacion-webflux"
resolve_s3 = false
s3_prefix = "webflux"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
[default.deploy.parameters]
stack_name = "webflux-dev"
resolve_s3 = true
s3_prefix = "webflux-dev"
confirm_changeset = true
image_repositories = []