AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Microservicio de Autenticación basado en Spring WebFlux, PostgreSQL, Docker, ECS Fargate.
  Este template.yaml será utilizado por GitHub Actions como orquestador de:
    - Infraestructura (Terraform)
    - Imagen Docker (Dockerfile)
    - Despliegue a ECR y ECS

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:

  # 🧱 (1) Infraestructura: Terraform
  # GitHub Actions ejecutará Terraform para crear:
  # - VPC, Subnets, Security Groups
  # - ECS Cluster + Service + TaskDefinition
  # - RDS PostgreSQL (opcional)
  # - IAM roles
  #
  # Terraform se ejecutará en el workflow de GitHub Actions, no aquí directamente.

  # 🐳 (2) Imagen Docker
  # El Dockerfile se encuentra en la raíz del microservicio
  # GitHub Actions construirá la imagen y la enviará a Amazon ECR

  # 📦 (3) Repositorio ECR (si se desea crear desde aquí)
  DockerImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: microservicio-autenticacion-webflux
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: >
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Eliminar imágenes antiguas",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # 🚀 (4) ECS Cluster y Service serán creados por Terraform

  # 👁️ (5) Monitoreo
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  # 🔍 URL final de ECS (ej: ALB DNS name), definirlo en Terraform
  AplicacionEndpoint:
    Description: URL final del microservicio autenticación en ECS
    Value: "http://alb-o-dns-ecs.autenticacion.com"
